export const MYSMARTCARD_ROLES = ['SUPER_ADMIN', 'OWNER', 'ADMIN'] as const

export type MySmartCardRole = (typeof MYSMARTCARD_ROLES)[number]

export const MYSMARTCARD_LEAD_STATUSES = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  INTERESTED: 'INTERESTED',
  QUALIFIED: 'QUALIFIED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PURCHASED: 'PURCHASED',
  FOLLOW_UP: 'FOLLOW_UP',
  CONVERTED: 'CONVERTED',
  LOST: 'LOST',
} as const

export const MYSMARTCARD_INTENTS = {
  GREETING: 'GREETING',
  PRODUCT_INFO: 'PRODUCT_INFO',
  PRODUCT_PRICING: 'PRODUCT_PRICING',
  PRODUCT_COMPARISON: 'PRODUCT_COMPARISON',
  PRODUCT_MEDIA_REQUEST: 'PRODUCT_MEDIA_REQUEST',
  ORDER_INTENT: 'ORDER_INTENT',
  PURCHASE_INTENT: 'PURCHASE_INTENT',
  SUPPORT: 'SUPPORT',
  SHIPPING: 'SHIPPING',
  PAYMENT: 'PAYMENT',
  REFUND: 'REFUND',
  RETURN: 'RETURN',
  OFFER: 'OFFER',
  HUMAN_AGENT: 'HUMAN_AGENT',
  OTHER: 'OTHER',
} as const

export type MySmartCardIntent = (typeof MYSMARTCARD_INTENTS)[keyof typeof MYSMARTCARD_INTENTS]

export const MYSMARTCARD_CONVERSATION_MODES = {
  AI: 'AI',
  HUMAN: 'HUMAN',
  HYBRID: 'HYBRID',
} as const

export const MYSMARTCARD_POLICY_TYPES = [
  'shipping',
  'delivery',
  'returns',
  'refunds',
  'replacement',
  'warranty',
  'payment',
  'cancellation',
] as const

export const LEAD_SCORE_SIGNALS = {
  ASKED_PRICING: 10,
  ASKED_PRODUCT_IMAGE: 5,
  ASKED_HOW_TO_PURCHASE: 15,
  ASKED_PAYMENT_DETAILS: 20,
  ASKED_QUANTITY: 15,
  ASKED_DELIVERY_TIME: 10,
  REPLIED_MULTIPLE_TIMES: 5,
  REQUESTED_HUMAN_AGENT: 0,
  PURCHASE_INTENT: 25,
  PROVIDED_CONTACT_INFO: 10,
} as const
